language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: JUNb7f1777zNpewi2B8cHaCkLXEZQAGgMmRJgy5CJ8f0cdSl38gq/quqPwn+WZyA+Yy8kKxl5HJdNLNnqk93CgH7/uRyxu3+YA7W7AQAR6/63LdH/u8a7jWNKVl7Ba6Fv5a4f8L/JYMpAyytEXSExeKyRy+rB/ni8kO8Qa+gPJ7FpYZP4fhvHC1wHnWMS5YvBW0A83AyJM48lqtzotfy0vV1u71C/71pXq90+bRylwdWh+yZy8pBdPLUNBplUlQjCBZs2nluswi+q550ktl6gkLb2NDGT7TBnk9BV8cguZRM37ZusZJ8bSzMx1V8yKMaYvCS9k8zPn2Pc71uLiPI+9D3T+VtGrHCrYGiNlncUjHUf/AwwlBLWXlNWcq25QVMqHdcpiQzVtjcslNkHDBvNn4+fGN05wsALH0XcSr1LihoIO/0WHTzcLkDSxBSnt58v/Grjtd1loqv5RLryXDCo6QXAWzhhSqB2Qov8fqpnUaKqLdiL4jvfDiPi9RB3dke7JiphXIpO6vZBAErC3ZXtDGxBOk+WiyyQygJt12JhE4DS/xR+St/A/7Avxpx96KwB1XPY10hgUIGLrxjJazi1RI3aJTufGnC6sb0GiPcmWykEiDtl7WuCYWidbLXr9yURmMWaA3G+KhTWZDlJHbczVJMydXSYDCWJ6ZHSekVdEA=