language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: UStE20BVpms+atq4k1Orc0qsD9tqmpK09FylCLiz5orTMjaNYIPOaWRGdeqGfpK/lzqEI9w1HM6sG+lemQSFwLUEXlTxiSAWST8fFx1DTdDTzXhL9xS3PlWsMtCSSWwrxzzOMkIf5nCPjMgkHDKN+mtwj2U5S2o22BRbb9p/mkTDtH1eppRdw5Qrpt0qWDegSU5y7DABje6VDzcRnrAO1ZgSV6HovFtKKPnEChEOEG0kkT5bS2y3v+qbB4GHAyy5ioDY9DOULjF9AYWS7sHQwQw2UCEGrJ0oCO8LbEXXqbxH5TbrAjvJQbBkrMVCUGpwaAq/3eoc3BCfrdpw58JNXEW8NhrvXh4UTZKGgTVpgar7po5hq3drMBb4Qfrfi9cXo/opfeux5oImPg7FWm8GeBhn1yvFWmDFj5PV+8SF/AsRbr5NaLen/MeCbE4LwGg0nt4Kuoa6OmGffxQ4ptVwfjPM80hGDT9VHXxM0oDHqMJvcUE/LtNnNGjxouPthYBXM1MO+hkjMtxDEXSSj6ayYP5LkTow19ICuzUNg3+M8LNjsPdi4h+TizKEXOpwYxirHWEbSC29JwasNhJX6feOWzsqB8m2hv+Mf10fgK7t7E/MdN+S/pXYIihqDLcXJGb7i9ET6H+/ubzPCDXQk6esRBipnx3ynr+BiXKtEPitxvc=